apiVersion: v1
kind: Service
metadata:
  namespace: wsb-sentiment
  name: wsb-sentiment
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31234
  selector:
    app: wsb-sentiment